// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.0
// source: protos/recommendation.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RecommendationServClient is the client API for RecommendationServ service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecommendationServClient interface {
	GetRecommendation(ctx context.Context, in *GetRecommendationReq, opts ...grpc.CallOption) (*GetRecommendationRep, error)
}

type recommendationServClient struct {
	cc grpc.ClientConnInterface
}

func NewRecommendationServClient(cc grpc.ClientConnInterface) RecommendationServClient {
	return &recommendationServClient{cc}
}

func (c *recommendationServClient) GetRecommendation(ctx context.Context, in *GetRecommendationReq, opts ...grpc.CallOption) (*GetRecommendationRep, error) {
	out := new(GetRecommendationRep)
	err := c.cc.Invoke(ctx, "/RecommendationServ/GetRecommendation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecommendationServServer is the server API for RecommendationServ service.
// All implementations must embed UnimplementedRecommendationServServer
// for forward compatibility
type RecommendationServServer interface {
	GetRecommendation(context.Context, *GetRecommendationReq) (*GetRecommendationRep, error)
	mustEmbedUnimplementedRecommendationServServer()
}

// UnimplementedRecommendationServServer must be embedded to have forward compatible implementations.
type UnimplementedRecommendationServServer struct {
}

func (UnimplementedRecommendationServServer) GetRecommendation(context.Context, *GetRecommendationReq) (*GetRecommendationRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecommendation not implemented")
}
func (UnimplementedRecommendationServServer) mustEmbedUnimplementedRecommendationServServer() {}

// UnsafeRecommendationServServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecommendationServServer will
// result in compilation errors.
type UnsafeRecommendationServServer interface {
	mustEmbedUnimplementedRecommendationServServer()
}

func RegisterRecommendationServServer(s grpc.ServiceRegistrar, srv RecommendationServServer) {
	s.RegisterService(&RecommendationServ_ServiceDesc, srv)
}

func _RecommendationServ_GetRecommendation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecommendationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServServer).GetRecommendation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RecommendationServ/GetRecommendation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServServer).GetRecommendation(ctx, req.(*GetRecommendationReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RecommendationServ_ServiceDesc is the grpc.ServiceDesc for RecommendationServ service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecommendationServ_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RecommendationServ",
	HandlerType: (*RecommendationServServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRecommendation",
			Handler:    _RecommendationServ_GetRecommendation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/recommendation.proto",
}
